backend/modules/wechat/controllers/ReplyDefaultController.php
<?php
namespace backend\modules\wechat\controllers;

use yii;
use common\models\wechat\ReplyDefault;

/**
 * 系统回复控制器
 * Class ReplyDefaultController
 * @package backend\modules\wechat\controllers
 */
class ReplyDefaultController extends WController
{

    /**
     * 首页
     */
    public function actionIndex()
    {
        $model = $this->findModel();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['index']);
        }

        return $this->render('index',[
            'model'         => $model,
        ]);
    }

    /**
     * 返回模型
     * @return array|ReplyDefault|null|yii\db\ActiveRecord
     */
    protected function findModel()
    {
        if (empty(($model = ReplyDefault::find()->one())))
        {
            return new ReplyDefault;
        }

        return $model;
    }
}

backend/modules/wechat/controllers/RuleController.php
<?php
namespace backend\modules\wechat\controllers;

use yii;
use yii\data\Pagination;
use common\models\wechat\Rule;
use common\models\wechat\RuleKeyword;

/**
 * 规则控制器
 * Class RuleController
 * @package backend\modules\wechat\controllers
 */
class RuleController extends WController
{
    /**
     * @return string
     * 首页
     */
    public function actionIndex()
    {
        $request  = Yii::$app->request;
        $module     = $request->get('module','');

        $type     = $request->get('type','');
        $keyword  = $request->get('keyword','');

        $where = [];
        switch ($type)
        {
            case '1':
                $where['status'] = 1;
                break;
            case '2':
                $where['status'] = -1;
                break;
        }

        $data   = Rule::find()->with('ruleKeyword')
            ->andFilterWhere(['module' => $module])
            ->andFilterWhere($where)
            ->andFilterWhere(['like', 'name', $keyword]);

        $pages  = new Pagination(['totalCount' =>$data->count(), 'pageSize' =>$this->_pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('displayorder desc,append desc')
            ->limit($pages->limit)
            ->all();

        return $this->render('index',[
            'modules'   => Rule::$moduleExplain,
            'module'   => $module,
            'models'  => $models,
            'pages'   => $pages,
            'type'    => $type,
            'keyword' => $keyword,
        ]);
    }

    /**
     * 编辑
     * @return mixed|string|yii\web\Response
     */
    public function actionEdit()
    {
        $request  = Yii::$app->request;
        $id       = $request->get('id');

        //回复规则
        $rule    = $this->findRuleModel($id);
        //默认关键字
        $keyword = new RuleKeyword();
        //基础
        $model     = $this->findModel($id);

        //关键字列表
        $ruleKeywords = [
            RuleKeyword::TYPE_MATCH => [],
            RuleKeyword::TYPE_REGULAR => [],
            RuleKeyword::TYPE_INCLUDE => [],
            RuleKeyword::TYPE_TAKE => [],
        ];

        if($rule['ruleKeyword'])
        {
            foreach ($rule['ruleKeyword'] as  $value)
            {
                $ruleKeywords[$value['type']][] = $value['content'];
            }
        }

        if ($rule->load(Yii::$app->request->post()) && $model->load(Yii::$app->request->post()) && $keyword->load(Yii::$app->request->post()))
        {
            $transaction = Yii::$app->db->beginTransaction();
            try
            {
                //编辑
                if($rule->save())
                {
                    //获取规则ID
                    $rule_id = $rule->isNewRecord ?  Yii::$app->db->getLastInsertID() : $rule->id;
                    $model->rule_id = $rule_id;
                    //其他匹配包含关键字
                    $otherKeywords = Yii::$app->request->post('ruleKey',[]);
                    $resultKeywords = $keyword->updateKeywords($keyword->content,$otherKeywords,$ruleKeywords,$rule_id,$this->_module,$rule);

                    if($model->save() && $resultKeywords)
                    {
                        $transaction->commit();
                        return $this->redirect(['reply/index','module'=>$rule->module]);
                    }
                }
            }
            catch (\Exception $e)
            {
                $transaction->rollBack();
                return $this->message($e->getMessage(),$this->redirect(['reply/index']),'error');
            }
        }

        return $this->render('edit',[
            'rule'          => $rule,
            'model'         => $model,
            'keyword'       => $keyword,
            'title'         => Rule::$moduleExplain[$this->_module],
            'ruleKeywords'  => $ruleKeywords,
        ]);
    }

    /**
     * ajax修改
     * @return array
     */
    public function actionUpdateAjax()
    {
        $id = Yii::$app->request->get('id');
        return $this->updateModelData($this->findRuleModel($id));
    }

    /**
     * 删除
     * @param $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if($this->findRuleModel($id)->delete())
        {
            return $this->message("删除成功",$this->redirect(['index']));
        }
        else
        {
            return $this->message("删除失败",$this->redirect(['index']),'error');
        }
    }

    /**
     * 返回模型
     * @param $id
     * @return $this|Rule|static
     */
    protected function findRuleModel($id)
    {
        if (empty($id))
        {
            $model = new Rule;
            $model->module = $this->_module;
            return $model->loadDefaultValues();
        }

        if (empty(($model = Rule::findOne($id))))
        {
            $model = new Rule;
            $model->module = $this->_module;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

backend/modules/wechat/controllers/SettingController.php
<?php
namespace backend\modules\wechat\controllers;

use yii;
use common\models\wechat\Setting;

/**
 * 参数设置控制器
 * Class SettingController
 * @package backend\modules\wechat\controllers
 */
class SettingController extends WController
{
    /**
     * 参数设置
     * @return string|yii\web\Response
     */
    public function actionHistoryStat()
    {
        if ($setting = Yii::$app->request->post('setting'))
        {
            $setting['msg_history_date']['value'] = (int)$setting['msg_history_date']['value'];

            $model = Setting::findModel();
            $model->history = serialize($setting);
            if($model->save())
            {
                return $this->redirect(['history-stat']);
            }
        }

        return $this->render('history-stat',[
            'list' => Setting::getSetting('history'),
        ]);
    }

    /**
     * 特殊消息回复
     * @return string|yii\web\Response
     */
    public function actionSpecialMessage()
    {
        if ($setting = Yii::$app->request->post('setting'))
        {
            $model = Setting::findModel();
            $model->special = serialize($setting);
            if($model->save())
            {
                return $this->redirect(['special-message']);
            }
        }

        return $this->render('special-message',[
            'list' => Setting::getSetting('special'),
        ]);
    }
}

backend/modules/wechat/views/setting/history-stat.php
<?php
use yii\widgets\ActiveForm;

$this->title = '参数';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="wrapper wrapper-content animated fadeInRight">
    <?php $form = ActiveForm::begin(); ?>
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>参数</h5>
            </div>
            <div class="ibox-content">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label"><?= $list['is_msg_history']['title'] ?></label>
                        <div>
                            <label><input name="setting[is_msg_history][status]" value="1" type="radio" <?= $list['is_msg_history']['status'] == 1 ? 'checked' : '' ?> > 开启</label>
                            <label><input name="setting[is_msg_history][status]" value="-1" type="radio" <?= $list['is_msg_history']['status'] == 1 ? '' : 'checked' ?>> 关闭</label>
                        </div>
                        <div class="hint-block">开启此项后，系统将记录用户与系统的往来消息记录。</div>
                        <div class="help-block"></div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="rule-name"><?= $list['msg_history_date']['title'] ?></label>
                        <input class="form-control" name="setting[msg_history_date][value]" value="<?= $list['msg_history_date']['value'] ?>" type="text">
                        <div class="hint-block">设置保留历史消息记录的天数，为0则为保留全部。</div>
                        <div class="help-block"></div>
                    </div>
                    <div class="form-group">
                        <label class="control-label"><?= $list['is_utilization_stat']['title'] ?></label>
                        <div>
                            <label><input name="setting[is_utilization_stat][status]" value="1" type="radio" <?= $list['is_utilization_stat']['status'] == 1 ? 'checked' : '' ?> > 开启</label>
                            <label><input name="setting[is_utilization_stat][status]" value="-1" type="radio" <?= $list['is_utilization_stat']['status'] == 1 ? '' : 'checked' ?> > 关闭</label>
                        </div>
                        <div class="hint-block">开启此项后，系统将记录用户与系统的往来消息记录。</div>
                        <div class="help-block"></div>
                    </div>
                  <div class="hr-line-dashed"></div>
                </div>
                <div class="form-group">　
                    <div class="col-sm-4 col-sm-offset-2">
                        <button class="btn btn-primary" type="submit">保存内容</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/modules/wechat/views/setting/special-message.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = '非文字回复 ';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li><a href="<?= Url::to(['rule/index'])?>"> 关键字自动回复</a></li>
                    <li class="active"><a href="<?= Url::to(['setting/special-message'])?>"> 非文字消息回复</a></li>
                    <li><a href="<?= Url::to(['reply-default/index'])?>"> 关注/默认回复</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active">
                        <div class="panel-body">
                            <?php $form = ActiveForm::begin(); ?>
                            <div class="col-sm-12">
                                <?php foreach ($list as $key => $row){ ?>
                                    <div class="form-group">
                                        <label class="control-label"><?= $row['title'] ?></label>
                                        <div>
                                            <label><input name="setting[<?= $key ?>][type]" value="1" type="radio" <?= $row['type'] == 1 ? 'checked' : '' ?> onclick="$(this).parent().parent().next().show();$(this).parent().parent().next().next().hide();"> 关键字</label>
                                            <label><input name="setting[<?= $key ?>][type]" value="2" type="radio" <?= $row['type'] == 1 ? '' : 'checked' ?> onclick="$(this).parent().parent().next().hide();$(this).parent().parent().next().next().show();"> 模块</label>
                                        </div>
                                        <div style="display: <?= $row['type'] == 1 ? 'block' : 'none' ?>">
                                            <input class="form-control" name="setting[<?= $key ?>][content]" value="<?= $row['content'] ?>" type="text">
                                        </div>
                                        <div style="display: <?= $row['type'] == 1 ? "none" : "block" ?>">
                                            <select name="setting[<?= $key ?>][module]" class="form-control">
                                                <option value="" selected>不处理(使用系统默认回复)</option>
                                                <!--<option value="custom">多客服转接</option>-->
                                            </select>
                                        </div>
                                        <div class="hint-block">如果【<?= $row['title'] ?>】到达时, 并且此时并不在对话上下文中, 将会采用选中的模块来处理. 如果选择"不处理", 那么这个消息将会使用系统默认回复来回复</div>
                                        <div class="help-block"></div>
                                    </div>
                                <?php } ?>
                                <div class="hr-line-dashed"></div>
                            </div>
                            <div class="form-group">　
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">保存内容</button>
                                </div>
                            </div>
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>